//
//  Spotify.swift
//
//
//  Created by Evan Anderson on 12/3/23.
//

import Foundation
import SwiftSovereignStates

// https://support.spotify.com/us/article/where-spotify-is-available/
struct Spotify : RegionServiceAvailabilityProtocol {
    var type : RegionServiceAvailabilityType {
        return RegionServiceAvailabilityType.spotify
    }
    
    var category : RegionServiceAvailabilityCategory {
        return RegionServiceAvailabilityCategory.music_service
    }
    
    var imageURL : String {
        return "2/26/Spotify_logo_with_text.svg/%quality%px-Spotify_logo_with_text.svg.png"
    }
    
    var websiteURL : String {
        return "https://spotify.com"
    }
    
    var supportedRegions : Set<Country> {
        return [
            Country.algeria,
            Country.angola,
            Country.benin,
            Country.botswana,
            Country.burkina_faso,
            Country.burundi,
            Country.cameroon,
            Country.cape_verde,
            Country.chad,
            Country.comoros,
            Country.ivory_coast,
            Country.democratic_republic_of_the_congo,
            Country.djibouti,
            Country.egypt,
            Country.ethiopia,
            Country.equatorial_guinea,
            Country.eswatini,
            Country.gabon,
            Country.gambia,
            Country.ghana,
            Country.guinea,
            Country.guinea_bissau,
            Country.kenya,
            Country.lesotho,
            Country.liberia,
            Country.libya,
            Country.madagascar,
            Country.malawi,
            Country.mali,
            Country.mauritania,
            Country.mauritius,
            Country.morocco,
            Country.mozambique,
            Country.namibia,
            Country.niger,
            Country.nigeria,
            Country.republic_of_the_congo,
            Country.rwanda,
            Country.sao_tome_and_principe,
            Country.senegal,
            Country.seychelles,
            Country.sierra_leone,
            Country.south_africa,
            Country.tanzania,
            Country.tunisia,
            Country.uganda,
            Country.zambia,
            Country.zimbabwe,
            
            Country.armenia,
            Country.azerbaijan,
            Country.bahrain,
            Country.bangladesh,
            Country.bhutan,
            Country.brunei,
            Country.cambodia,
            Country.georgia,
            Country.hong_kong,
            Country.india,
            Country.indonesia,
            Country.iraq,
            Country.israel,
            Country.japan,
            Country.jordan,
            Country.kuwait,
            Country.kyrgyzstan,
            Country.laos,
            Country.lebanon,
            Country.macau,
            Country.malaysia,
            Country.maldives,
            Country.mongolia,
            Country.nepal,
            Country.oman,
            Country.pakistan,
            Country.palestine,
            Country.philippines,
            Country.qatar,
            Country.saudi_arabia,
            Country.singapore,
            Country.south_korea,
            Country.sri_lanka,
            Country.taiwan,
            Country.tajikistan,
            Country.thailand,
            Country.timor_leste,
            Country.united_arab_emirates,
            Country.uzbekistan,
            Country.vietnam,
            
            //Country.aland,
            Country.albania,
            Country.andorra,
            Country.anguilla,
            //Country.ascension,
            Country.austria,
            //Country.azores,
            //Country.balearic_islands,
            Country.belarus,
            Country.belgium,
            Country.bermuda,
            Country.bosnia_and_herzegovina,
            Country.british_virgin_islands,
            Country.bulgaria,
            //Country.canary_islands,
            Country.cayman_islands,
            //Country.ceuta,
            Country.croatia,
            Country.cyprus,
            Country.czech_republic,
            Country.denmark,
            Country.estonia,
            Country.falkland_islands,
            Country.faroe_islands,
            Country.finland,
            Country.france,
            //Country.french_guiana,
            Country.french_polynesia,
            Country.germany,
            Country.gibraltar,
            Country.greece,
            Country.greenland,
            Country.guadeloupe,
            Country.guernsey,
            Country.hungary,
            Country.iceland,
            Country.ireland,
            Country.isle_of_man,
            Country.italy,
            Country.jersey,
            Country.kazakhstan,
            Country.kosovo,
            Country.latvia,
            Country.liechtenstein,
            Country.lithuania,
            Country.luxembourg,
            //Country.madeira,
            Country.malta,
            //Country.martinique,
            //Country.mayotte,
            //Country.melilla,
            Country.moldova,
            Country.monaco,
            Country.montenegro,
            Country.montserrat,
            Country.netherlands,
            Country.new_caledonia,
            Country.north_macedonia,
            Country.norway,
            //Country.pitcairn_islands,
            Country.poland,
            Country.portugal,
            Country.romania,
            //Country.reunion,
            Country.saint_barthelemy,
            Country.saint_helena_ascension_and_tristan_da_cunha,
            Country.saint_martin,
            Country.saint_pierre_and_miquelon,
            Country.san_marino,
            Country.serbia,
            Country.slovakia,
            Country.slovenia,
            Country.spain,
            //Country.svalbard,
            Country.sweden,
            Country.switzerland,
            //Country.tristan_da_cunha,
            Country.turkey,
            Country.turks_and_caicos_islands,
            Country.ukraine,
            Country.united_kingdom,
            Country.wallis_and_futuna,
            
            Country.american_samoa,
            Country.antigua_and_barbuda,
            Country.bahamas,
            Country.barbados,
            Country.belize,
            Country.canada,
            Country.costa_rica,
            Country.curacao,
            Country.dominica,
            Country.dominican_republic,
            Country.el_salvador,
            Country.grenada,
            Country.guam,
            Country.guatemala,
            Country.haiti,
            Country.honduras,
            Country.jamaica,
            Country.mexico,
            Country.nicaragua,
            Country.northern_mariana_islands,
            Country.panama,
            Country.puerto_rico,
            Country.saint_kitts_and_nevis,
            Country.saint_lucia,
            Country.saint_vincent_and_the_grenadines,
            Country.trinidad_and_tobago,
            Country.united_states,
            Country.united_states_virgin_islands,
            
            Country.argentina,
            Country.aruba,
            Country.bolivia,
            Country.brazil,
            Country.chile,
            Country.colombia,
            Country.ecuador,
            Country.guyana,
            Country.paraguay,
            Country.peru,
            //Country.sint_maarten,
            Country.suriname,
            Country.uruguay,
            Country.venezuela,
            
            Country.australia,
            //Country.bonaire,
            //Country.christmas_island,
            //Country.cocos_islands,
            Country.cook_islands,
            Country.fiji,
            Country.kiribati,
            Country.marshall_islands,
            Country.micronesia,
            Country.nauru,
            Country.new_zealand,
            Country.niue,
            Country.norfolk_island,
            Country.palau,
            Country.papua_new_guinea,
            //Country.saba,
            Country.samoa,
            //Country.sint_eustatius,
            Country.solomon_islands,
            Country.tokelau,
            Country.tonga,
            Country.tuvalu,
            Country.vanuatu
        ]
    }
}
